export const stdVer = '0.63.0'
export { copy, move, expandGlob } from 'https://deno.land/std@0.63.0/fs/mod.ts'
export { TextProtoReader } from 'https://deno.land/std@0.63.0/textproto/mod.ts'
export { BufReader } from 'https://deno.land/std@0.63.0/io/bufio.ts'
export { join } from 'https://deno.land/std@0.63.0/path/mod.ts'
export * as path from 'https://deno.land/std@0.63.0/path/mod.ts'
export * as fmt from 'https://deno.land/std@0.63.0/fmt/colors.ts'
export { parse } from 'https://deno.land/std@0.63.0/flags/mod.ts'
