export const stdVer = '0.66.0'
export { copy, move, expandGlob, ensureDirSync } from 'https://deno.land/std@0.66.0/fs/mod.ts'
export { TextProtoReader } from 'https://deno.land/std@0.66.0/textproto/mod.ts'
export { BufReader } from 'https://deno.land/std@0.66.0/io/bufio.ts'
export { join, basename } from 'https://deno.land/std@0.66.0/path/mod.ts'
export * as path from 'https://deno.land/std@0.66.0/path/mod.ts'
export * as fmt from 'https://deno.land/std@0.66.0/fmt/colors.ts'
export { parse } from 'https://deno.land/std@0.66.0/flags/mod.ts'
export { PDFDocument, PDFPage, degrees } from 'https://cdn.pika.dev/pdf-lib@^1.7.0'
